Added ALERT pin functionality
adafruit/Adafruit_INA260 pull request #8
Opened 2019-11-07 15:38 UTC by m0ivq

Added ALERT pin specific functions.

2019-11-19 09:11 UTC, m0ivq commented
All travis errors now fixed.

2019-11-19 16:37 UTC, siddacious requested changes
Awesome @m0ivq ! Thanks for your work, this looks great. I'd like to test it before merging; Could I trouble you to write a simple sketch that exercises the new code? Ideally with some setup instructions. It needn't be a magnum opus, just something like whatever you used to test as you were writing the code.

Thank you! This would help me test the code quicker and get it merged ASAP.

2020-11-05 13:31 UTC, dougie181 commented
I have tested the alert functionality by setting the OVERVOLTAGE alert and it worked fine. Thanks @m0ivq for your great work!

In my scenario, I use the alert to trigger an external interrupt to wakeup when the voltage is over 3v.

`boolean initINA260Sensor() {

  if (!ina260.begin()) {
     Serial.println("Couldn't find INA260 chip");
     return false;
  }

  // setup the alert functionality
  ina260.setAlertLimit(3000);
  ina260.setAlertType(INA260_ALERT_OVERVOLTAGE);

  return true;
}`

2020-11-06 19:05 UTC, siddacious requested changes
I only left one specific comment but it looks like you need to merge `adafruit/master` into your branch.

The `.github` directory should stay and the travis config should not be resurrected ;)

At first glance it code looks good so please fix the above and I will test. 

Thank you for your contribution! This was one is close to my <3

2020-11-06 19:05 UTC, siddacious commented on library.properties
> +version=1.3.2
Looks like an old version; This should be bumped to 1.4.0 and the dependencies should remain

2020-11-06 19:08 UTC, siddacious commented
@m0ivq Please also add and example that demonstrates the new functionality. That will help with testing and will help users to use your contribution.

Thank you!

2020-11-06 19:23 UTC, m0ivq commented
@siddacious something went wrong when I merged into my branch so reverted it back but ran out of time to try again. I'll try again on Monday once I've added a few examples. I can confirm that overcurrent is definitely working correctly as it's been in use daily in a test fixture at my work since the original PR!

2021-02-17 14:01 UTC, m0ivq commented
I've cleaned up the PR but don't have access to hardware to test at the moment.

2021-02-17 21:20 UTC, ladyada commented
please run clang-format again - reply when the PR is passing CI

2021-02-17 21:25 UTC, closed without merging